export default {
  loginImage: require('./loginImage.png'),
  otpImage: require('./otpImage.png'),
  signupImage: require('./signupImage.png'),
  askVirtualVaidya: require('./askVirtualVaidya.png'),
  tabSelectImage: require('./tabSelectImage.png'),
  illness1: require('./illness1.png'),
  bookmarkImage: require('./bookmarkImage.png'),
  ayurvedicImage: require('./ayurvedicImage.png'),
  hospitalImage: require('./hospitalImage.png'),
  yogaImage: require('./yogaImage.png'),
  exclusiveTherapyImage: require('./exclusiveTherapyImage.png'),
  panchKarma: require('./panchKarma.png'),
  startUnfilled: require('./startUnfilled.png'),
  startFilled: require('./startFilled.png'),
  featured1: require('./featured1.png'),
  featured2: require('./featured2.png'),
  featured3: require('./featured3.png'),
  featured4: require('./featured4.png'),
  immunityWellness: require('./immunityWellness.png'),
  ayurvedicProduct: require('./ayurvedicProduct.png'),
  homeopathicProducts: require('./homeopathicProducts.png'),
  personalCare: require('./personalCare.png'),
  constantImg1: require('./constantImg1.png'),
  constantImg2: require('./constantImg2.png'),
  constantImg3: require('./constantImg3.png'),
  constantImg4: require('./constantImg4.png'),
};
